version: '3.3'
services:
  flask:
    image: 'flask:latest'
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  express:
    image: 'express:latest'
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
  nginx:
    image: 'nginx:1-alpine'
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
    - '8080:80'
    depends_on:
      - flask
      - express