version: '3.3'
services:
  flask:
    image: 'flask:latest'
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  express:
    image: 'express:latest'
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
  react:
    image: 'react:latest'
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
    - '8000:8000'
