version: '3.3'
services:
  laravel:
    image: dagume/nginx-php7.3-ideasoft:latest
    volumes:
      - ./laravel:/var/www/html
    ports:
      - '8088:80'
  flask:
    image: 'flask:latest'
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  express:
    image: 'express:latest'
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
    - '3000:3000'