version: '3.3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
