version: '3.3'
services:
  flask:
    image: 'flask:latest'
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role == worker]
  express:
    image: 'express:latest'
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role == worker]