version: '3'

services:
  flask:
    image: 'nicobytes/flask:latest'
    deploy:
      mode: replicated
      replicas: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.flask-http.rule=Host(`nicobytes.site`)
        - traefik.http.routers.flask-http.entrypoints=http
        - traefik.http.routers.flask-https.rule=Host(`nicobytes.site`)
        - traefik.http.routers.flask-https.entrypoints=https
        - traefik.http.routers.flask-https.tls=true
        - traefik.http.routers.flask-https.tls.certresolver=le
        - traefik.http.services.flask.loadbalancer.server.port=8888
    networks:
      - traefik-public
      - default
  express:
    image: 'nicobytes/express:latest'
    ports:
      - '3000:3000'
    deploy:
      mode: replicated
      replicas: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.flask.rule=Host(`flask.nicobytes.site`)
    networks:
      - traefik-public
      - default


networks:
  traefik-public:
    external: true