version: '3'

services:
  flask:
    image: 'nicobytes/flask:latest'
    ports:
      - '8888:8888'
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role==worker]
  express:
    image: 'nicobytes/express:latest'
    ports:
      - '3000:3000'
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role==worker]