version: "3"
services:
  app:
    image: dagume/nginx-php7.3-ideasoft:latest
    volumes:
      - .:/var/www/html
    links:
      - pgsql
    ports:
      - 8089:80
  pgsql:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: turismo
    ports:
      - 5435:5432